### PR TITLE
Avoid numbers in enums for Swift compatibility

### PR DESCRIPTION
**Pull request by koke**
Since `WPAnalyticsStat` is the name of the enum, Swift will remove that
as a prefix so you can do things like `.LoginFailed`.

In #36, a number of 3D Touch related constants were introduced, which
would be mapped as `.3DTouchShortcut*` enum values. As I understand it,
Swift names can't start with a digit, which is probably why the compiler
was only stripping the `WPAnalytics` prefix but leaving the `Stats`, and
all the enum references in Swift were broken.

analytics-swift-enums

I know it's not really called Force Touch on the iPhone, so feel free to
use an alternative, as long as it doesn't start with a digit.

Linking to the frameworks issue for reference: https://github.com/wordpress-mobile/WordPress-iOS/issues/4434

Needs Review: @kwonye

### CODE REVIEW

**Comment by astralbodies** [comment]
ThreeD :smile:

**Comment by koke** [comment]
I considered ThreeD, ThreeDee, TD, or just leave it at Shortcut. ¯\_(ツ)_/¯

**Comment by kwonye** [comment]
> ThreeD
> or just leave it at Shortcut

^ Can we change to one of those please? Either one works for me :blush:

**Comment by koke** [comment]
Shortcut it is then :)

**Comment by kwonye** [comment]
:+1: :shipit: :100: :8ball:

**Pull request merged**
