### PR TITLE
Adds some analytics events for helpshift.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Adds a few events to solve https://github.com/wordpress-mobile/WordPress-iOS/issues/3470.

Also removes these events, which we can't track:
- `WPAnalyticsStatSupportSentMessage`
- `WPAnalyticsStatSupportSentReplyToSupportMessage`

For more information check out the issue linked above.

**How to test:**

Just make sure the code builds and the unit tests run.

### CODE REVIEW

**Comment by astralbodies** [comment]
@diegoreymendez (following up from our DM) Can you check to see if similar changes have been or are planned on being made in the Android app?

**Comment by diegoreymendez** [comment]
@astralbodies - Android is not tracking these events right now.

That said, these events were suggested by @oguzkocer and accepted by @sendhil as a possible addition [in this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/3463).

@oguzkocer - Can you please handle adding these to Android, or creating an issue on Androids side for it?  Thanks!

**Comment by diegoreymendez** [comment]
@astralbodies - I just created an [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/4751) for it in the Android repo.

**Comment by astralbodies** [comment]
@diegoreymendez :shipit: 

Not sure what Travis' problem is though.

**Comment by diegoreymendez** [comment]
Ty @astralbodies !

**Pull request merged**
