### PR TITLE
Adds WPAnalyticsStatPushNotificationAlertPressed Metric

### PR DESCRIPTION
**Pull request by jleandroperez**
/cc @sendhil (Thank you sir!)

### CODE REVIEW

**Comment by sendhil** [comment]
@jleandroperez is there a corresponding Android addition?

**Comment by jleandroperez** [comment]
@sendhil as far as i understand, we'll be also adding it in Android, but i can't find the ticket (Dan is AFK until next week). 

This would be the [Wordpress iOS Related Issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/3384).

**Comment by sendhil** [comment]
Looks good.
:shipit:

**Comment by sendhil** [comment]
@jleandroperez pushed a new pod version(0.0.29) that contains this enum.

**Comment by jleandroperez** [comment]
@sendhil *Awesome*!! thank you Sendhil!!

**Pull request merged**
