### PR TITLE
Improve framework support

### PR DESCRIPTION
**Pull request by koke**
Sets header_dir to WordPressComAnalytics to avoid problems with
underscores/dashes in names.

I'd bump the minor version since this breaks backwards compatibility,
but I'm not sure what to do since it's 0.0

See https://github.com/wordpress-mobile/WordPress-iOS/issues/4434

Needs Review: @kwonye

### CODE REVIEW

**Comment by koke** [comment]
Merged develop, ready for review

**Comment by koke** [comment]
Found an issue with bundles and the data model, don't merge yet

**Comment by koke** [comment]
Never mind, I keep confusing Analytics with Tracks, problem is with a different pod :tired_face:

**Comment by kwonye** [comment]
Whoops, sorry @koke I forgot the iOS side prefers to merge in themselves. Looked great though :shipit:

**Pull request merged**
